services:
  - type: web
    name: groovelab
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.esgrhmrypqfjnsdwhlvx:James19775%402025@aws-1-eu-central-1.pooler.supabase.com:5432/postgres
      - key: SESSION_SECRET
        generateValue: true
      - key: PORT
        value: 10000
